### ISSUE TITLE
Current status of webpage functionality

### ISSUE THREAD

**Issue by attikis** [cms-PdmV/GrASP#131] opened 2022-10-25 09:32 UTC
**Describe the bug:**

**To reproduce:**
4. See wrong value

**Expected behavior:**

**Screenshots (optional):**

**Browser (optional, please fill in only if you are experiencing visual bugs):**
Browser name [e.g. chrome, firefox, safari]

**Additional context (optional):**

**Comment by jordan-martins** [comment] 2022-10-27 12:42
the problem is a consequence of the drawing function… db fetch is fine, however, drawing not… easy solution is to cut the drawing objects by fixing the number of rows appending the rest in different pages.

Best,
Jordan

**Comment by attikis** [comment] 2022-10-27 12:46
hi,

indeed today i got the primary table but the page just froze. I can't interact with it. I am using safari on macOS ventura, but i have tried in the past using firefox with no discernible difference.

If what jordan suggest is indeed the case, the the proposed solution would be ok i guess. From my end I don;'t use it to browse samples but too search for particular ones. So i think it makes sense to truncate the table if nRows > nCutOff.

Cheers,
Alexandros

**Comment by ggonzr** [comment] 2022-10-27 13:54
Dear all,

I am working on fixing this. I hope to finish this issue on the next week

I remain attentive in case of updates

Regards

Geovanny

**Comment by attikis** [comment] 2022-10-27 13:59
Hi Geovanny,

thanks a lot! Looking forward to an update.

Cheers,
Alexandros

**Comment by ggonzr** [comment] 2022-10-31 12:05
Dear Alexandros (@attikis ),

GrASP web application has been updated. Now, samples data linked to a tag are split in different sub pages. Therefore, you will not experience again a freeze issue when you scroll through the page. Please give it a look and in case of issues, I remain attentive to check them

Best regards

Geovanny

**Comment by attikis** [comment] 2022-10-31 13:08
Hi Geovanny,

great! I will have a look shortly

Cheers,
Alexandros

**Comment by attikis** [comment] 2022-10-31 13:48
Hi again,

It does behave much better than last time so things have improved.
Let me use it a bit more and i'll report additional problems.

Thank you,
Alexandros

**Comment by ggonzr** [comment] 2022-11-11 09:45
Dear all,

Since the last update, I have not received reports of new issues. Therefore, I assume this problem is completely solved and it is possible to close this issue. Please feel free of reopen it in case you find problems related.

Best regards

Geovanny

**Closed by ggonzr** 2022-11-11 09:45 UTC
